language: objective-c

before_script: 
  #!/bin/sh
  set -e
  brew update
  brew install xctool
  pod install
script: 
  #!/bin/sh
  set -e
  xctool -workspace login.workspace -scheme login build test
