language: objective-c
 
branches:
 only:
 - master
    
xcode_workspace: Wanderluster.xcworkspace
xcode_scheme: WanderlusterTests
osx_image: xcode7
xcode_sdk: iphonesimulator9.0

script:
- xcodebuild clean build test -workspace Wanderluster.xcworkspace -scheme WanderlusterTests -sdk iphonesimulator9.0 dONLY_ACTIVE_ARCH=NO
